FROM debian:latest

# Instalar tini y iptables, además de herramientas de red
RUN apt-get update 

# Instalar iptables
RUN apt-get install -y iptables

# Instalar para ping(Es util)
RUN apt-get install iputils-ping -y

#framework para el firewall
RUN apt install shorewall -y



# Copiar archivos de configuración personalizados
COPY zones /etc/shorewall/zones
COPY interfaces /etc/shorewall/interfaces
COPY policy /etc/shorewall/policy
COPY rules /etc/shorewall/rules
COPY snat /etc/shorewall/snat
COPY hosts /etc/shorewall/hosts


#Inicia shorewall
#RUN shorewall start

# Habilitar el inicio automático de Shorewall en el contenedor
RUN echo "startup=1" > /etc/default/shorewall


# Exponer los puertos que sean necesarios para el firewall
EXPOSE 80 443

# Iniciar Shorewall al iniciar el contenedor
CMD ["shorewall", "start"]
#ADD config_firewall.sh /bin
#RUN chmod +x /bin/config_firewall.sh

#ENV CHAIN "DOCKER-FIREWALL"
#ENV OPEN_PORTS "22, 443, 80"
#ENV ACCEPT_ALL_FROM ""

#ENTRYPOINT ["/sbin/tini", "--"]
#CMD ["/bin/config_firewall.sh"]
