services:
  firewall_debian:
    build: 
      dockerfile: dockerfile
    container_name: firewall_debian
    ports:
      - "15173:5173"
      - "4000:4000"
    cap_add:
      - NET_ADMIN
    privileged: true
    tty: true
    command: tail -f /dev/null
    networks:
      net_external:
        ipv4_address: 172.168.10.10  # Dirección IP en la red externa
      net_internal:
        ipv4_address: 10.0.10.10     # Dirección IP en la red interna
networks:
  net_external:
    external: true 
  net_internal:
    external: true