services:
  front_debian:
    build: 
      dockerfile: dockerfile
    container_name: front
    ports:
      - "5173:5173"
    cap_add:
      - NET_ADMIN
    tty: true
    command: tail -f /dev/null
    privileged: true  
    networks:
      net_internal:
        ipv4_address: 10.0.10.11  # Dirección IP en la red interna
   #entrypoint: /bin/bash -c "tail -f /dev/null"
    entrypoint: /bin/bash -c "/SERVICE/config.sh && tail -f /dev/null"
networks: 
  net_internal:
    external: true