FROM debian:latest

USER root
#Directorio de trabajo
WORKDIR /SERVICE
# Copia el front
COPY /back /SERVICE/back
#Copia el back
COPY /front /SERVICE/front

#Actualiza la paquetera e instala las herramientas necesarias
RUN apt-get update -y && apt-get install -y \
    iproute2 \
    net-tools \
    curl \
    iputils-ping

#Instalacion de nodejs
RUN apt-get install nodejs npm -y

# Instala las dependencias del back-end
WORKDIR /SERVICE/back
RUN npm install

# Instala las dependencias del front-end
WORKDIR /SERVICE/front
RUN npm install

#Copia es script para las configuraciones
COPY config.sh /SERVICE/

#Le da permisos para ejecutarse
RUN chmod +x /SERVICE/config.sh

EXPOSE 5173
