name: db

services:

  db:
    build: 
      dockerfile: dockerfile
    container_name: database
    restart: always
    ports:
      - "13306:3306"
    networks:
      net_internal:
        ipv4_address: 10.0.10.12 # Solo red interna
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_USER: usermy
      MYSQL_PASSWORD: usermy
      MYSQL_ROOT_PASSWORD: usermy

networks: 
  net_internal:
    external: true