FROM debian:latest

USER root
#Directorio de trabajo
WORKDIR /FRONT
# Copia el front
COPY /back /FRONT/front
#Copia el back
COPY /front /FRONT/back

#Actualiza la paquetera e instala las herramientas necesarias
RUN apt-get update -y && apt-get install -y \
    iproute2 \
    net-tools \
    curl 

#Instalacion de nodejs
RUN apt-get install nodejs npm -y

#Copia es script para las configuraciones
COPY config.sh /FRONT/

#Le da permisos para ejecutarse
RUN chmod +x /FRONT/config.sh
